package net.sf.libgrowl.internal

trait Headers{
  val messageBuilder: MessageBuilder = new MessageBuilder
  private def newHeader(headerName: String) = new MessageHeader(messageBuilder, headerName)

  val ORIGIN_MACHINE_NAME: MessageHeader = newHeader("Origin-Machine-Name")
  val ORIGIN_PLATFORM_NAME: MessageHeader = newHeader("Origin-Platform-Name")
  val ORIGIN_PLATFORM_VERSION: MessageHeader = newHeader("Origin-Platform-Version")
  val ORIGIN_SOFTWARE_NAME: MessageHeader = newHeader("Origin-Software-Name")
  val ORIGIN_SOFTWARE_VERSION: MessageHeader = newHeader("Origin-Software-Version")
  val APPLICATION_NAME: MessageHeader = newHeader("Application-Name")
  val APPLICATION_ICON: MessageHeader = newHeader("Application-Icon")
  val NOTIFICATION_COUNT: MessageHeader = newHeader("Notifications-Count")
  val NOTIFICATION_INTERNAL_ID: MessageHeader = newHeader("X-Data-Internal-Notification-ID")
  val NOTIFICATION_ID: MessageHeader = newHeader("Notification-ID")
  val NOTIFICATION_NAME: MessageHeader = newHeader("Notification-Name")
  val NOTIFICATION_DISPLAY_NAME: MessageHeader = newHeader("Notification-Display-Name")
  val NOTIFICATION_TITLE: MessageHeader = newHeader("Notification-Title")
  val NOTIFICATION_ENABLED: MessageHeader = newHeader("Notification-Enabled")
  val NOTIFICATION_ICON: MessageHeader = newHeader("Notification-Icon")
  val NOTIFICATION_TEXT: MessageHeader = newHeader("Notification-Text")
  val NOTIFICATION_STICKY: MessageHeader = newHeader("Notification-Sticky")
  val NOTIFICATION_PRIORITY: MessageHeader = newHeader("Notification-Priority")
  val NOTIFICATION_COALESCING_ID: MessageHeader = newHeader("Notification-Coalescing-ID")
  val NOTIFICATION_CALLBACK_TARGET: MessageHeader = newHeader("Notification-Callback-Target")
  val NOTIFICATION_CALLBACK_CONTEXT: MessageHeader = newHeader("Notification-Callback-Context")
  val NOTIFICATION_CALLBACK_CONTEXT_TYPE: MessageHeader = newHeader("Notification-Callback-Context-Type")
  val NOTIFICATION_CALLBACK_RESULT: MessageHeader = newHeader("Notification-Callback-Result")
  val NOTIFICATION_CALLBACK_TIMESTAMP: MessageHeader = newHeader("Notification-Callback-Timestamp")
  val RESPONSE_ACTION: MessageHeader = newHeader("Response-Action")
  val ERROR_CODE: MessageHeader = newHeader("Error-Code")
  val ERROR_DESCRIPTION: MessageHeader = newHeader("Error-Description")
  val IDENTIFIER: MessageHeader = newHeader("Identifier")
  val LENGTH: MessageHeader = newHeader("Length")
}
